spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data/payrecord;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
      sformat_sql: true
jwt:
  secret: 1234567890123456789012345678901234567890

logging:
  level:
    org.hibernate.type: trace


resources:
  static-locations:
  servlet:
    multipart:
    max-file-size: 20MB

parayo:
  file-upload:
    default-dir: /parayo

