spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parayo_db?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: parayo
    password: parayo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
      sformat_sql: true
jwt:
  secret: 1234567890123456789012345678901234567890

logging:
  level:
    org.hibernate.type: trace


resources:
  static-locations:
  servlet:
    multipart:
    max-file-size: 20MB

parayo:
  file-upload:
    default-dir: /parayo

